name: test
on: ["push", "pull_request"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: pdm install
      - name: test
        run: pdm run ./tests/__init__.py

  ci-success:
    name: ci
    if: ${{ success() }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: exit 0


